# Generated by Django 5.2.1 on 2025-10-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childmenu',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='submenu',
            name='is_active',
        ),
        migrations.AddField(
            model_name='childmenu',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public (No Login Required)'), ('authenticated', 'Login Required'), ('department', 'Department Based')], default='public', max_length=20),
        ),
        migrations.AddField(
            model_name='menu',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public (No Login Required)'), ('authenticated', 'Login Required'), ('department', 'Department Based')], default='public', max_length=20),
        ),
        migrations.AddField(
            model_name='submenu',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public (No Login Required)'), ('authenticated', 'Login Required'), ('department', 'Department Based')], default='public', max_length=20),
        ),
    ]
